### ISSUE TITLE
Possibility to claim rewards from wallet for delegators

### ISSUE THREAD

**Issue by xarnodo** [xar-network/wallet#11]
At this moment, the delegators do not have clear visibility of the rewards generated by their delegations, and do not have the option to claim them autonomously.

It would be an improvement to display this information directly in each user's wallet and offer them the possibility to claim and re-delegate as needed.

Thank you!

**Comment by andrecronje** [comment]
Issue has a dependency on;

https://github.com/xar-network/javascript-sdk/issues/1 and https://github.com/xar-network/javascript-sdk/issues/2

Will move to @antonnell after those two improvements are closed

**Comment by andrecronje** [comment]
#1 and #2 closed in v2.17.8

Reference examples here; https://github.com/xar-network/examples/blob/master/README.md#staking

**Comment by andrecronje** [comment]
Deployed in a0db1ffdcc0233b6d5cba9560242515529190a4c

**Comment by xarnodo** [comment]
Thank you!
