### ISSUE TITLE
Initial value (0) not being removed automatically when inputting new value on FTM/CSDT input slot.

### ISSUE THREAD

**Issue by MichaelChentom** [xar-network/wallet#6]
When trying to mint CSDT and selecting the collateral amount in FTM we see that the initial value of 0 stays after inputting a new value. 

I tried to input a value of 10,000 FTM as a collateral, but because the original 0 was still there it became 100,000 FTM.

**Comment by MichaelChentom** [comment]
![d326252f3c3ba9a5de90ae850acf7750](https://user-images.githubusercontent.com/57908233/70376453-939a8980-1909-11ea-8e5c-78d29f6ce823.gif)

**Comment by antonnell** [comment]
Deployed in a0db1ff
