### ISSUE TITLE
Public XAR address not fully visible within the CSDT Portal

### ISSUE THREAD

**Issue by jayspace-crypto** [xar-network/wallet#7]
Public XAR address not fully visible within the CSDT Portal

The full Public XAR address is not fully visible without using the 'Zoom Out' of the web browser. 
Also the right click copy option when using Firefox does not copy the full address.

Please add a built in 'Copy' option in order to copy the full public XAR address for ease, otherwise stakers are potentially going to try to send to an incorrect incomplete address. 

Thanks

**Comment by antonnell** [comment]
There isn't enough real-estate to show at all resolutions. I changed the breakpoints to switch to a different layout earlier. Added a onMoueHover event to display a tooltip and reduced the font size a bit. You should have options to see the full address now. Copying the address, even when the ellipsis is there, will still copy the full address.

Deployed in a0db1ff
