### ISSUE TITLE
Cancel button doesn't work

### ISSUE THREAD

**Issue by giuseppefrancaviglia** [xar-network/wallet#8]
After the wallet is unlocked (keyStore + password), click on the "Send icon" (upper right of the page); it is shown a form with 2 fields (destination and amount) and 2 buttons (Cancel and Send); the click on the Cancel button doesn't work.
<img width="322" alt="Schermata 2019-12-09 alle 20 57 01" src="https://user-images.githubusercontent.com/58706740/70481488-027f0a80-1ae3-11ea-908b-4a3358cdb9e1.png">

**Comment by antonnell** [comment]
Deployed in a0db1ff
